name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build project
        run: ./gradlew build --no-daemon --stacktrace

      - name: Set current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Set unique tag name
        run: echo "TAG_NAME=v${CURRENT_DATE}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Zip built files
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mkdir -p release
          zip -r "release/traccar-${CURRENT_DATE}.zip" target/

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
          files: release/traccar-${{ env.CURRENT_DATE }}.zip
